### PR TITLE
:memo: docs(self-hosting): Add deployment tutorial and link for Alibaba cloud

### PR DESCRIPTION
**Pull request by LYH-RAIN**
Add deployment tutorial and link for Alibaba cloud
A more detailed deployment tutorial can be found in the official Alibaba Cloud interface for deploying Maybe.
As shown in the figure below.
image

### CODE REVIEW

**Comment by LYH-RAIN** [comment]
Hello, we are from the Alibaba Cloud Compute Nest team. We are dedicated to making various open-source projects easier and faster to host in the cloud. We found your open-source project very meaningful, so we spontaneously built a self-hosted version on Alibaba Cloud based on your documentation and Docker Compose. The current version of the service will be deployed on the user’s own ECS, and the deployment version we provide is free; only the user's server, namely the ECS, will incur charges. Finally, we hope Alibaba Cloud can be a way for you to deploy quickly. Thank you very much.

**Comment by zachgoll** [comment]
@LYH-RAIN unfortunately, we are not accepting these types of contributions, but appreciate the tutorial!

The reason is because as a small team, we must provide user support for all documented deployment options.  We are intentionally keeping the "official" list narrow so that we can provide better support for our small list of documented options.

**Comment by LYH-RAIN** [comment]
Although it's a bit of a pity, I respect your decision. In fact, any subsequent versions of this software on Alibaba Cloud will be maintained by us, and we guarantee that it will be updated to the latest version. If we receive any user feedback, we will promptly relay it to you. Therefore, if you consider supporting more self-hosting options in the future, please remember to contact me at [lyh376240@alibaba-inc.com](mailto:lyh376240@alibaba-inc.com).

**Comment by LYH-RAIN** [comment]
> Although it's a bit of a pity, I respect your decision. In fact, any subsequent versions of this software on Alibaba Cloud will be maintained by us, and we guarantee that it will be updated to the latest version. If we receive any user feedback, we will promptly relay it to you. Therefore, if you consider supporting more self-hosting options in the future, please remember to contact me at [lyh376240@alibaba-inc.com](mailto:lyh376240@alibaba-inc.com).

@zachgoll

**Comment by zachgoll** [comment]
@LYH-RAIN sounds good!  In the meantime, you're more than welcome to maintain a fork of the repo that has these instructions for users who might find it helpful.

**Pull request closed without merging**
