### PR TITLE
Filter transactions by category

### PR DESCRIPTION
**Pull request by ThibautGrx**
closes https://github.com/maybe-finance/maybe/issues/579

### CODE REVIEW

**Comment by ThibautGrx** [comment]
I've tried to fix some small UI dysfunctions at the same time.
- Tick/untick the checkbox when clicking on the label
- Keep the dropdown opened when clicking on tabs

However, the dropdown closes when selecting a category (or account) because turbo stream replace the whole turbo frame "transactions_search_form". Thoughts on how we could fix it ?

**Review by zachgoll — COMMENTED** [review]
Looks good!

In regards to the dropdown closing when a category is selected, we've got updated designs coming soon that will introduce an "apply filters" button on each of these tabs so the user can select multiple options and then explicitly reload the results.

Until those are ready, I think this behavior is okay for the moment.

**Comment by zachgoll** [comment]
@ThibautGrx was doing one last check on this prior to merging and noticed that when the category filter is applied, the "badge" does not show up.

Can you update this so those are added?  Here's where the core of that logic is happening, and you can use #578 as a reference as well.

https://github.com/maybe-finance/maybe/blob/b1bfdef8ffa6ef3b43a7b7cc12f898d2f4771365/app/models/transaction.rb#L23-L42

**Comment by ThibautGrx** [comment]
You're right , I went a little fast... here's the update

**Review by zachgoll — APPROVED** [review]
Awesome, thanks for the update, looks good!

**Pull request merged**
