### PR TITLE
Fixed code to store correct accountable_type

### LINKED ISSUE #381: Entry method step not properly setting type
Currently the "entry method" step is hard-coded to type "Depository" when it should detect which type from the `params[:type]`

https://github.com/maybe-finance/maybe/blob/main/app/views/accounts/new.html.erb#L45-L47
```
<%= render "entry_method", type: Account::Depository.new, text: 'Enter account balance manually', icon: "keyboard" %>
<%= render "entry_method", type: Account::Depository.new, text: 'Securely link bank account with data provider (coming soon)', icon: "link-2", disabled: true %>
<%= render "entry_method", type: Account::Depository.new, text: 'Upload spreadsheet (coming soon)', icon: "sheet", disabled: true %>
```

### PR DESCRIPTION
**Pull request by sarvaiyanidhi**
Closes #381

### CODE REVIEW

**Comment by Shpigford** [comment]
(@sarvaiyanidhi I appreciate you trying multiple things on that ruby scan/brakeman issue. I don't know the solution, but just wanted to say thanks for the repeated effort. 🙃)

**Comment by sarvaiyanidhi** [comment]
Thank you for the appreciation @Shpigford . I am still figuring out solution though I am checking from whitelisted accountable_types I am not sure of issue.

**Comment by sarvaiyanidhi** [comment]
@Shpigford There is already reported issue related to this in brakeman 

https://github.com/presidentbeef/brakeman/issues/1115

Does this help?

**Comment by sarvaiyanidhi** [comment]
Closing this in favor of better solution implemented in #395

**Review by Hongkh168 — COMMENTED** [review]
Hi

**Pull request closed without merging**
