### PR TITLE
Minor improvements to categories & changelog pages

### PR DESCRIPTION
**Pull request by arsenstorm**
Hey there!

I’m testing the hosted version of Maybe, and a few things bothered me regarding the UI.

The grey border around the badges for the categories feels *wrong*. I’ve updated this to match the colour of the badge instead.

Before:

Screenshot 2024-10-09 at 21 38 30

After:

Screenshot 2024-10-09 at 21 38 55

It also feels a bit wrong to see the name of the changelog update instead of the person who created the release.

Before:

Screenshot 2024-10-09 at 21 42 09

After:

Screenshot 2024-10-09 at 21 41 31

### CODE REVIEW

**Comment by zachgoll** [comment]
@arsenstorm thanks for the updates! 

@justinfar will have to approve these as I'm not the best with design :)

**Comment by arsenstorm** [comment]
Awesome; thank you!

**Comment by justinfar** [comment]
Hey @arsenstorm thanks so much for looking into this

Re changing the name to show the person who created the release, 100% agree

Re the border color, initially I had the `alpha-black/25` that blended with the background which gave it a darkened category background color which is exactly what you're doing here (albeit slightly more subdued) 

Figma handles borders/strokes differently in comparison to actual CSS so this probably got a bit lost in translation. 

So overall agree on the change, only thing I'd change is the to make the border slightly lighter and perhaps change from 25% to 30% over here:

```ruby
border-color: color-mix(in srgb, <%= category.color %> 25%, white);
``` 

If you have other UI bits that you think could be improved feel free to let us know :)

**Comment by arsenstorm** [comment]
Ah I see

I think switching 25% -> 30% does make it slightly nicer

Another option is to make it borderless which would align better with the tags and merchants page; however, I personally feel like the badges on these pages would benefit more with a border (or a slightly darker background)

**Pull request merged**
