### PR TITLE
Improve Sidebar UI

### LINKED ISSUE #647: Improvement: Add trendlines and styling to sidebar account list
CleanShot 2024-04-18 at 14 35 30

## Designs

Below are the designs you should follow while implementing this:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2828-2845&mode=design&t=Y0hF2UeUXaOhxGL4-0

## Overview

This issue is for getting the sidebar accounts list in parity with the official designs.

## Requirements

_If there is a missing / incorrect requirement, please leave a comment before starting work on this._

- [ ] Add trendline and percent change to account balance
- [ ] Add a period selector (above the list) and allow the following values: `Period.last_7_days`, `Period.last_30_days`.  Default should be `Period.last_30_days`.  Labels should be `7D` and `1M`
- [ ] Add icons left of account name (we don't have bank logos yet, so use the placeholder value design for all accounts)

## Implementation Suggestions

_Below are some ideas for implementation to get you started.  Use your best judgment here—if there's a better way to do things, go for it!_

- Most of the backend logic for calculating the trendlines and percent change by period is already completed.  See: https://github.com/maybe-finance/maybe/blob/f5f624881f3b8900fa56d655ec040b5ee5d8a0af/app/models/account.rb#L68

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
  - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
  - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

### PR DESCRIPTION
**Pull request by syedbarimanjan**
## Requirements
 
 * [x]  Add trendline and percent change to account balance
 * [x]  Add a period selector (above the list) and allow the following values: `Period.last_7_days`, `Period.last_30_days`.  Default should be `Period.last_30_days`.  Labels should be `7D` and `1M`
 * [x]  Add icons left of account name (we don't have bank logos yet, so use the placeholder value design for all accounts)
 
Fixes #647
/claim #647

[Screencast from 23-04-2024 11:29:31.webm](https://github.com/maybe-finance/maybe/assets/112156147/ced71c8d-d012-4b80-a9f7-6cad211c1b69)

I have added all of the requirements, just time_series chart is giving errors which I am trying to solve.

### CODE REVIEW

**Review by zachgoll — COMMENTED** [review]
This is a good start but I think there are a few things we'll want to address prior to merging.  I left some specific comments within the code, but we'll also want to make sure the UI matches the [designs](https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2828-2845&mode=design&t=Y0hF2UeUXaOhxGL4-0).  I'm seeing a few inconsistencies, screenshotted below:

CleanShot 2024-04-23 at 09 55 38

CleanShot 2024-04-23 at 10 00 22

**Comment by syedbarimanjan** [comment]
> This is a good start but I think there are a few things we'll want to address prior to merging. I left some specific comments within the code, but we'll also want to make sure the UI matches the [designs](https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2828-2845&mode=design&t=Y0hF2UeUXaOhxGL4-0). I'm seeing a few inconsistencies, screenshotted below:
> 
> CleanShot 2024-04-23 at 09 55 38
> 
> CleanShot 2024-04-23 at 10 00 22

Yeah I made these changes locally will push them there is just one big problem which I am stuck on is that the favorable_direction and trend.direction are not updataing they are the same for all of these trendlines so thier color is the same

**Comment by zachgoll** [comment]
> > This is a good start but I think there are a few things we'll want to address prior to merging. I left some specific comments within the code, but we'll also want to make sure the UI matches the [designs](https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2828-2845&mode=design&t=Y0hF2UeUXaOhxGL4-0). I'm seeing a few inconsistencies, screenshotted below:
> > CleanShot 2024-04-23 at 09 55 38
> > CleanShot 2024-04-23 at 10 00 22
> 
> Yeah I made these changes locally will push them there is just this one problem which I am trying to solve is that the favorable_direction and trend.direction are not updating they are the same for all of these trendlines so thier color is the same

It looks like you _may_ need to specify the `favorable_direction` in the `series` method on `account` (think we might have missed adding this when we updated time series charts):

https://github.com/maybe-finance/maybe/blob/1f6e83ee911fcdc618c6fa08ae9e2b8a9c0adb93/app/models/account.rb#L53-L66

**Comment by syedbarimanjan** [comment]
@JoshAntBrown Hey, I'm feeling pretty under the weather. Mind splitting with me?

**Comment by JoshAntBrown** [comment]
I'm away for the weekend now so not sure I'll get any time to look at this.

**Comment by zachgoll** [comment]
@syedbarimanjan I'm going to mark this as a draft for now.  When this is ready for another review just mark it as ready and I'll take a look.

**Comment by syedbarimanjan** [comment]
@jakubkottnauer hey mind splitting with me and completing this?

**Comment by jakubkottnauer** [comment]
> @jakubkottnauer hey mind splitting with me and completing this?

I won't be able to pick up new work until Thursday. I can take over if this is not finished by then.

**Comment by zachgoll** [comment]
Thanks for the work on this.  Closing this out as we've merged the completed bounty in #697

**Pull request closed without merging**
