### PR TITLE
Add reusable modal

### PR DESCRIPTION
**Pull request by robzolkos**
Closes https://github.com/maybe-finance/maybe/issues/360

This adds a `modal` helper method.  This wraps the complexity of rendering a modal such that you just need to wrap your view with this helper:

```
<%= modal do %>
  .. view you want displayed in modal ...
<% end %
```

To trigger the display of the modal - any link or button that should open a modal needs to specify to use the modal turbo frame

`<%= link_to "Open Modal", some_path, data: { turbo_frame: "modal" }`

The modal will close on ESC and clicking away from it.  It includes a backdrop that is currently the browser default but can be styled further.

This PR doesn't add any styling/headers/footers to the actual modal.  It simply provides the mechanism to open/close a modal using standard rails/hotwire.

It  looks like this:

CleanShot 2024-02-07 at 14 04 29

- [x] Escape closes
- [x] Dark background when open
- [x] Clicking outside closes
- [x] Modal shell styling to match Figma
- [x] Document use

### CODE REVIEW

**Comment by robzolkos** [comment]
@Shpigford question on styling (re figma).  Do we want it as _close_ as possible to the Figma using Tailwind defaults, or do we want to style is _exactly_ as per the Figma file (I don't mind either way but there are some colors, shadows that are not default TW, so will need to slap the config around a bit.

**Comment by Shpigford** [comment]
> @Shpigford question on styling (re figma). Do we want it as _close_ as possible to the Figma using Tailwind defaults, or do we want to style is _exactly_ as per the Figma file (I don't mind either way but there are some colors, shadows that are not default TW, so will need to slap the config around a bit.

Ideally _exactly_, including creating new colors and shadows in Tailwind config.

**Comment by Shpigford** [comment]
Great job on this!

**Comment by zackgilbert** [comment]
@robzolkos Learned a couple of things from this PR, so thank you!

**Pull request merged**
