### PR TITLE
Feature: Support Teller Part 1: Teller API client

### PR DESCRIPTION
**Pull request by tmyracle**
This is the start of work on supporting Teller for #19 . Taking a different approach here and trying to do smaller PRs since this will be a big change that doesn't need to go all in one. All the backend work can be done in pieces and then drop in the Teller Connect component in the UI to actually expose to users. 

The scope of this PR is to set up the following:
- Define types for all Teller API responses and webhooks
- Create typesafe Teller API client 
- Define Teller webhook endpoint and handle the webhook.test event
- Add middleware to validate Teller webhook signature per their docs
- Stub the TellerService (implementation will be separate PR)
- Add required env vars
- Also refactored crypto.service to use the native crypto module since CryptoJS is no longer being maintained: [CryptoJS support discontinued](https://github.com/brix/crypto-js?tab=readme-ov-file#discontinued)
- Remove advisor service from `yarn dev`

Future work:
- Implement Teller service to implement relevant account connection providers
- Write necessary ETL to map transactions and other models
- Update prisma schema with necessary Teller fields
- Add in Teller Connect UI 
- Add tests
- Potentially more as we dig in

As always all feedback, complaints, memes, etc more than welcome!

### CODE REVIEW

**Comment by spewmaker** [comment]
Hi Tyler, I would like to contribute to the backend for Teller incrementally, I am facing some issues setting up the project correctly, I have followed documentation so far and tried mimicking your forked repo as well.
Are there any other channels of communication to discuss the project? Slack or Discord by any chance.

**Comment by tmyracle** [comment]
> Hi Tyler, I would like to contribute to the backend for Teller incrementally, I am facing some issues setting up the project correctly, I have followed documentation so far and tried mimicking your forked repo as well. Are there any other channels of communication to discuss the project? Slack or Discord by any chance.

Hey! Yeah there's a [Discord](https://discord.gg/Xw54HTVYm8), but if you're having trouble getting the project to run from a fresh pull then I'd recommend [opening an issue](https://github.com/maybe-finance/maybe/issues/new/choose) and we can troubleshoot from there, otherwise the back and forth gets lost in Discord.

**Comment by tmyracle** [comment]
> @tmyracle Teller has an Institution API endpoint here: https://api.teller.io/institutions
> 
> 
> 
> EDIT: Stevie from Teller mentioned this: 
> 
> 
> 
> > the only thing that you shouldn't rely on there is "capabilities". The name is being changed to something else soon to make it fully public.

Oh awesome! I'll dig into this

**Comment by Shpigford** [comment]
@tmyracle You're ready for this to be merged, correct? (It's not set as Draft, but just wanted to make sure it was ready for merge)

**Comment by tmyracle** [comment]
> @tmyracle You're ready for this to be merged, correct? (It's not set as Draft, but just wanted to make sure it was ready for merge)

Yep, assuming everyone (you I guess? lol) is cool with the direction and these pieces. Will continue with more PRs building off this.

**Pull request merged**
