### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xshubham**
Fixed typo

### CODE REVIEW

**Comment by 1p22geo** [comment]
I was literally first

**Comment by 1p22geo** [comment]
#294

**Comment by Shpigford** [comment]
> I was literally earlier

Be kind please.

**Comment by Shpigford** [comment]
@xshubham Thanks for this! PR #294 fixes this plus a couple of other things, so going to close this. I appreciate you catching things like this!

**Comment by xshubham** [comment]
> @xshubham Thanks for this! PR #294 fixes this plus a couple of other things, so going to close this. I appreciate you catching things like this!

Oh, that's great. @1p22geo You're correct. Sorry, I didn't check the open PRs before submitting my change.

**Pull request closed without merging**
