### PR TITLE
Improve Local Dev Setup Documentation and Contribution Guidelines

### PR DESCRIPTION
**Pull request by zachgoll**
We've had several local setup issues and self-hosting questions:

- #335 
- #316 
- #306 
- #295 
- #292

The goal of this PR is to consolidate all of these into one spot.

I've updated the README and CONTRIBUTING guide alongside some additional setup guides in the Wiki:

- [Self Hosting](https://github.com/maybe-finance/maybe/wiki/Self-Hosting-Setup-Guide)
- [Mac Setup](https://github.com/maybe-finance/maybe/wiki/Mac-Dev-Setup-Guide)
- [Linux Setup](https://github.com/maybe-finance/maybe/wiki/Linux-Dev-Setup-Guide)
- [Windows Setup](https://github.com/maybe-finance/maybe/wiki/Windows-Dev-Setup-Guide)

These guides are a WIP and will be centralized places for us to communicate the best way to get started for local development and self-hosting.

### CODE REVIEW

**Comment by cartwatson** [comment]
As someone currently trying to get this setup for dev this looks useful to me.  Only thing that stood out was line 38 of the README, it gets rid of the shell syntax highlighting, admittedly not that useful but better to have it imo.

**Comment by robzolkos** [comment]
This is amazingly well done 👏🏻 

Notice in the individual setup guides in the wiki it mentions setting up Node - however - so far - the codebase doesn't need it (using importmaps instead).

**Comment by zachgoll** [comment]
@robzolkos good point, will remove those for now!

**Comment by leemcalilly** [comment]
Should using Docker with the dev container be included or are y'all thinking about moving away from that?

**Comment by zachgoll** [comment]
@leemcalilly are you referring to adding a dedicated guide for developing locally with Dev Containers?

@robzolkos may have to jump in on that one—I'm not using the Dev Container myself but I've seen a few questions surrounding it.

**Pull request merged**
