### PR TITLE
Add sidebar portfolio holdings

### LINKED ISSUE #6: Build sidebar portfolio listing
CleanShot 2024-01-02 at 13 44 32@2x

Note: You do *not* have to build the actual account outputs. This is primarily about stubbing out the frontend visuals.

Scope:
1. "Total portfolio" block
2. Portfolio listing
3. "New portfolio" link (link_to is `new_portfolio_path`)

Figma file: https://www.figma.com/file/rAn2k5U86nXZmBixAEsjdN/Shell?type=design&node-id=0%3A1&mode=design&t=0q11JqWuYDnEcFDH-1

### PR DESCRIPTION
**Pull request by jespr**
CleanShot 2024-01-02 at 12 24 26@2x

@Shpigford fixes #6. question: the dollar amount color is white (#ffffff) in Figma. But that color isn't part of our tailwind colors anymore, we use the Maybe-white which is #F8F9FA. Do we want to use `text-[#ffffff]` for the dollar amounts, that's what I'm doing currently.

### CODE REVIEW

**Comment by Shpigford** [comment]
@jespr We can use the Tailwind `text-white` instead. Also, you can remove the Dashboard/Portfolios links.

**Comment by jespr** [comment]
@Shpigford I don't think we can since I overrode that here https://github.com/maybe-finance/maybe/blob/main/config/tailwind.config.js#L12 :/ based on this:

CleanShot 2024-01-02 at 12 35 50@2x

**Comment by Shpigford** [comment]
@jespr Sorry, I mean we can just use `text-white` instead of `text-[#ffffff]`.

**Comment by jespr** [comment]
@Shpigford all ready to go

**Pull request merged**
