### PR TITLE
Improvement: D3 Line Chart Styles and Formatting

### LINKED ISSUE #643: Improvement: D3 Line Chart Styles and Formatting
CleanShot 2024-04-18 at 11 18 01

## Designs

Below are the designs you should follow while implementing this:

https://www.figma.com/file/lonJmVk3HYkwZoIO7xYP2w/Maybe-App-(Community)?type=design&node-id=2770-226&mode=design&t=Y0hF2UeUXaOhxGL4-0

## Overview

The current D3 line chart (`line_chart_controller.js`) we are using is lacking several design aspects and features.  This issue is dedicated to getting this chart to a near-"final" state.

## Requirements

_If there is a missing / incorrect requirement, please leave a comment before starting work on this._

### Functional Requirements

- [ ] Currently, we have a `trendline_controller.js` and a `line_chart_controller.js`.  We should consolidate these into a single `line_chart_controller` that is configurable.  Options will include:
  - [ ] Hide or display x-axis labels ("trendlines" have no axis) - show by default
  - [ ] Enable or disable tooltips ("trendlines" have no tooltip) - enable by default
- [ ] The chart controller will always receive a `TimeSeries.new([]).to_json` value, which can be an instance of `Money` or a regular integer (this is already implemented).  As part of this issue, we need to make sure the chart can handle both `Money` values and regular integers (including percentages) in the tooltip.
- [ ] When the chart is supplied with a **single value** or an "empty" Time Series (i.e. `TimeSeries.new([])`), it should display the "empty" state design.

### Design Requirements

- [ ] Implement gradient underneath the line (very subtle, see designs)
- [ ] Ensure padding and spacing matches designs
- [ ] When the _overall_ trend of the series that is passed to the line chart is "bad" (decreasing for an asset, increasing for a liability), the chart should go from a green color to a red color.
- [ ] When hovering over a data point in the chart, the line should highlight for dates prior to it, and the line after it should be grayed out

## Implementation Suggestions

_Below are some ideas for implementation to get you started.  Use your best judgment here—if there's a better way to do things, go for it!_

- Be sure to read through [time series code](https://github.com/maybe-finance/maybe/tree/main/app/models/time_series) as it will help conceptualize things for this issue
- In Maybe 1.0, we had the gradients implemented using a "Zero Point Gradient" trick with D3.  The code linked below is written in React/Visx (a wrapper around D3), but it may help give some ideas on how to achieve the gradient.
  - https://github.com/maybe-finance/maybe-archive/blob/04bf3d135bdbb1fdaa2dd669dca4738c797cc382/libs/client/shared/src/components/charts/time-series/Line.tsx#L67-L104

## Reminders

- Make sure to review our [contributing guidelines](https://github.com/maybe-finance/maybe/blob/main/CONTRIBUTING.md) before starting on an issue
- We do our best to define a clear spec for new features and fixes, but think of them as "suggestions", not "hard requirements".  We welcome ideas and suggestions!
  - If you see missing requirements to this issue, please leave a comment below explaining what is missing and why it is important.
  - If you see a requirement that you think is _incorrect_ or _not optimal_, please leave a comment explaining what you think needs to change below.

## Bounty
There is a $250 bounty on this. To participate in the bounty:

1. Comment `/attempt #643` to indicate you plan on working on this.
2. Submit a draft PR once you start and include `/claim #643` along with your general game plan for how you intent to implement this.
3. Change out of draft mode on the PR once you're ready to submit your attempt.
4. Include a short video showing functionality in your PR (drastically speeds up us approving).

In the event of multiple attempts, we generally pick the one that most closes matches the scope with the cleanest code and test coverage (when appropriate).

### PR DESCRIPTION
**Pull request by syedbarimanjan**
closes #643
/claim #643

### Functional Requirements
* [x]  Currently, we have a `trendline_controller.js` and a `line_chart_controller.js`.  We should consolidate these into a single `line_chart_controller` that is configurable.  Options will include:

   * [x]  Hide or display x-axis labels ("trendlines" have no axis) - show by default
   * [x]  Enable or disable tooltips ("trendlines" have no tooltip) - enable by default
 * [x]  When the chart is supplied with a **single value** or an "empty" Time Series (i.e. `TimeSeries.new([])`), it should display the "empty" state design.
* [x]  The chart controller will always receive a `TimeSeries.new([]).to_json` value, which can be an instance of `Money` or a regular integer (this is already implemented).  As part of this issue, we need to make sure the chart can handle both `Money` values and regular integers (including percentages) in the tooltip.

### Design Requirements
 * [x]  When the _overall_ trend of the series that is passed to the line chart is "bad" (decreasing for an asset, increasing for a liability), the chart should go from a green color to a red color.
 * [x]  Ensure padding and spacing matches designs
 * [x]  When hovering over a data point in the chart, the line should highlight for dates prior to it, and the line after it should be grayed out
 * [x]  Implement gradient underneath the line (very subtle, see designs)
 

* [ ] Refactor and improve overall styling

### CODE REVIEW

**Comment by syedbarimanjan** [comment]
* [ ]  The chart controller will always receive a `TimeSeries.new([]).to_json` value, which can be an instance of `Money` or a regular integer (this is already implemented).  As part of this issue, we need to make sure the chart can handle both `Money` values and regular integers (including percentages) in the tooltip.
@zachgoll can you further explain this.

**Comment by zachgoll** [comment]
> * [ ]   The chart controller will always receive a `TimeSeries.new([]).to_json` value, which can be an instance of `Money` or a regular integer (this is already implemented).  As part of this issue, we need to make sure the chart can handle both `Money` values and regular integers (including percentages) in the tooltip.
> 
> @zachgoll can you further explain this.

This basically just means that the D3 line chart should expect a `TimeSeries` data type as input, and since `TimeSeries` can hold multiple types of values (i.e. it can be a "money series" or just a "value series"), we need to make sure that our D3 chart can identify the value type and access the value properly.

The design file shows both a "Money Series" and "Percentage Series" (savings rate) as _examples_, so as long as the D3 chart appropriately handles both of these you should be all set.

**Comment by syedbarimanjan** [comment]
> > * [ ]    The chart controller will always receive a `TimeSeries.new([]).to_json` value, which can be an instance of `Money` or a regular integer (this is already implemented).  As part of this issue, we need to make sure the chart can handle both `Money` values and regular integers (including percentages) in the tooltip.
> > 
> > @zachgoll can you further explain this.
> 
> This basically just means that the D3 line chart should expect a `TimeSeries` data type as input, and since `TimeSeries` can hold multiple types of values (i.e. it can be a "money series" or just a "value series"), we need to make sure that our D3 chart can identify the value type and access the value properly.
> 
> The design file shows both a "Money Series" and "Percentage Series" (savings rate) as _examples_, so as long as the D3 chart appropriately handles both of these you should be all set.

can you provide an example of percentage as where or how it will be used, there is a percent value in trend that will be the percent the chart will show?

**Comment by zachgoll** [comment]
@syedbarimanjan there is an example of a percent-based chart in the provided design file (last example) that shows how the tooltip and trend is displayed.  To determine whether the chart displays a percentage value, I think we may want to add some sort of configuration option to the chart which tells it _how_ to access and format the data points (this could also apply to `Money` values).

**Comment by syedbarimanjan** [comment]
> @syedbarimanjan there is an example of a percent-based chart in the provided design file (last example) that shows how the tooltip and trend is displayed. To determine whether the chart displays a percentage value, I think we may want to add some sort of configuration option to the chart which tells it _how_ to access and format the data points (this could also apply to `Money` values).

I meant a real example of it being used somewhere in the software.

**Comment by zachgoll** [comment]
> > @syedbarimanjan there is an example of a percent-based chart in the provided design file (last example) that shows how the tooltip and trend is displayed. To determine whether the chart displays a percentage value, I think we may want to add some sort of configuration option to the chart which tells it _how_ to access and format the data points (this could also apply to `Money` values).
> 
> I meant a real example of it being used somewhere in the software. If it isnt at the moment can you specify where it will be used so i can try to implement it or just use it with some mock data which will help me better understand it.

Got it, understood now.  We do not have an implementation of this yet in the UI.  I'd recommend creating a small placeholder series somewhere in the UI to test it.  Something like:

```
<% series = TimeSeries.new([{ date: 2.days.ago.to_date, value: 88 }, { date: 1.day.ago.to_date, value: 89 }, { date: Date.today, value: 91 }]) %>
<div 
  data-controller="line-chart" 
  class="w-full h-full" 
  id="lineChart"
  data-line-chart-series-value="<%= series.to_json %>"
>
</div>
```

**Comment by syedbarimanjan** [comment]
Closing this as it has been better implemented in #657.

**Comment by syedbarimanjan** [comment]
closing this in favour of #657

**Pull request closed without merging**
